// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULLneSziS2x-w2QoZTlN1bd8qCsqMK_8',
    appId: '1:983223031453:web:b0b80f3a2a59df035e6674',
    messagingSenderId: '983223031453',
    projectId: 'autoclean-a9797',
    authDomain: 'autoclean-a9797.firebaseapp.com',
    storageBucket: 'autoclean-a9797.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXSyFdzhK-mliMUe2yoBF5mdrAzb5o3Lw',
    appId: '1:983223031453:android:53fee611ddf454405e6674',
    messagingSenderId: '983223031453',
    projectId: 'autoclean-a9797',
    storageBucket: 'autoclean-a9797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxFsPatETq6GqjcQo-8sa6XJSTJy5BnI',
    appId: '1:983223031453:ios:9b7a0b1318a734105e6674',
    messagingSenderId: '983223031453',
    projectId: 'autoclean-a9797',
    storageBucket: 'autoclean-a9797.appspot.com',
    iosBundleId: 'ci.onetek.autoclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxFsPatETq6GqjcQo-8sa6XJSTJy5BnI',
    appId: '1:983223031453:ios:9b7a0b1318a734105e6674',
    messagingSenderId: '983223031453',
    projectId: 'autoclean-a9797',
    storageBucket: 'autoclean-a9797.appspot.com',
    iosBundleId: 'ci.onetek.autoclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDULLneSziS2x-w2QoZTlN1bd8qCsqMK_8',
    appId: '1:983223031453:web:e39f51251cc22a375e6674',
    messagingSenderId: '983223031453',
    projectId: 'autoclean-a9797',
    authDomain: 'autoclean-a9797.firebaseapp.com',
    storageBucket: 'autoclean-a9797.appspot.com',
  );
}
